      # Warning: indentation here matters!

      - pytorch_windows_build:
          name: pytorch_windows_vs2017_14.11_py36_cuda10.1_build
          cuda_version: "10"
          python_version: "3.6"
          vc_version: "14.11"
          vc_year: "2017"
          vc_product: "BuildTools"
          use_cuda: "1"
          requires:
            - setup
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
      - pytorch_windows_test:
          name: pytorch_windows_vs2017_14.11_py36_cuda10.1_test1
          test_name: pytorch-windows-test1
          cuda_version: "10"
          python_version: "3.6"
          vc_version: "14.11"
          vc_year: "2017"
          vc_product: "BuildTools"
          use_cuda: "1"
          requires:
            - setup
            - pytorch_windows_vs2017_14.11_py36_cuda10.1_build
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
      - pytorch_windows_test:
          name: pytorch_windows_vs2017_14.11_py36_cuda10.1_test2
          test_name: pytorch-windows-test2
          cuda_version: "10"
          python_version: "3.6"
          vc_version: "14.11"
          vc_year: "2017"
          vc_product: "BuildTools"
          use_cuda: "1"
          requires:
            - setup
            - pytorch_windows_vs2017_14.11_py36_cuda10.1_build
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
      - pytorch_windows_build:
          name: pytorch_windows_vs2017_14.16_py36_cuda10.1_build
          cuda_version: "10"
          python_version: "3.6"
          vc_version: "14.16"
          vc_year: "2017"
          vc_product: "BuildTools"
          use_cuda: "1"
          requires:
            - setup
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
      - pytorch_windows_test:
          name: pytorch_windows_vs2017_14.16_py36_cuda10.1_test1
          test_name: pytorch-windows-test1
          cuda_version: "10"
          python_version: "3.6"
          vc_version: "14.16"
          vc_year: "2017"
          vc_product: "BuildTools"
          use_cuda: "1"
          requires:
            - setup
            - pytorch_windows_vs2017_14.16_py36_cuda10.1_build
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
      - pytorch_windows_test:
          name: pytorch_windows_vs2017_14.16_py36_cuda10.1_test2
          test_name: pytorch-windows-test2
          cuda_version: "10"
          python_version: "3.6"
          vc_version: "14.16"
          vc_year: "2017"
          vc_product: "BuildTools"
          use_cuda: "1"
          requires:
            - setup
            - pytorch_windows_vs2017_14.16_py36_cuda10.1_build
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
      - pytorch_windows_build:
          name: pytorch_windows_vs2019_py36_cuda10.1_build
          cuda_version: "10"
          python_version: "3.6"
          vc_version: ""
          vc_year: "2019"
          vc_product: "Community"
          use_cuda: "1"
          requires:
            - setup
      - pytorch_windows_test:
          name: pytorch_windows_vs2019_py36_cuda10.1_test1
          test_name: pytorch-windows-test1
          cuda_version: "10"
          python_version: "3.6"
          vc_version: ""
          vc_year: "2019"
          vc_product: "Community"
          use_cuda: "1"
          requires:
            - setup
            - pytorch_windows_vs2019_py36_cuda10.1_build
      - pytorch_windows_test:
          name: pytorch_windows_vs2019_py36_cuda10.1_test2
          test_name: pytorch-windows-test2
          cuda_version: "10"
          python_version: "3.6"
          vc_version: ""
          vc_year: "2019"
          vc_product: "Community"
          use_cuda: "1"
          requires:
            - setup
            - pytorch_windows_vs2019_py36_cuda10.1_build
