      - pytorch_android_gradle_build-x86_32:
          name: pytorch-linux-xenial-py3-clang5-android-ndk-r19c-gradle-build-x86_32
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
          requires:
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_build

      - pytorch_android_gradle_build:
          name: pytorch-linux-xenial-py3-clang5-android-ndk-r19c-gradle-build
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
          requires:
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_build
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_64_build
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v7a_build
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v8a_build
