      - pytorch_linux_build:
          name: nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_build
          build_environment: "pytorch-linux-xenial-py3-clang5-android-ndk-r19c-x86_32"
          requires:
            - setup
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:f990c76a-a798-42bb-852f-5be5006f8026"
          filters:
            branches:
              only: nightly
      - pytorch_linux_build:
          name: nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_64_build
          build_environment: "pytorch-linux-xenial-py3-clang5-android-ndk-r19c-x86_64"
          requires:
            - setup
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:f990c76a-a798-42bb-852f-5be5006f8026"
          filters:
            branches:
              only: nightly
      - pytorch_linux_build:
          name: nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v7a_build
          build_environment: "pytorch-linux-xenial-py3-clang5-android-ndk-r19c-arm-v7a"
          requires:
            - setup
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:f990c76a-a798-42bb-852f-5be5006f8026"
          filters:
            branches:
              only: nightly
      - pytorch_linux_build:
          name: nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v8a_build
          build_environment: "pytorch-linux-xenial-py3-clang5-android-ndk-r19c-arm-v8a"
          requires:
            - setup
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:f990c76a-a798-42bb-852f-5be5006f8026"
          filters:
            branches:
              only: nightly

      - pytorch_android_gradle_build:
          name: nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_android_gradle_build
          requires:
            - nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_build
            - nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_64_build
            - nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v7a_build
            - nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v8a_build
          filters:
            branches:
              only: nightly

      - pytorch_android_publish_snapshot:
          name: nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_android_publish_snapshot
          requires:
            - nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_android_gradle_build
          context: org-member
          filters:
            branches:
              only: nightly
